### Numpy

Is is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. 

Here we will cover:

1. Numpy Basics
2. focussing on arrays
3. Vectorized operations
 

In [1]:
!pip install numpy

In [2]:

import numpy as np

# create arrays using numpy
# create a 1D array

array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5]


In [3]:
print(type(array_1d))

<class 'numpy.ndarray'>


In [4]:
print(array_1d.shape)

(5,)


In [5]:
array_1d.reshape(5, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
array_2d=np.array([[1, 2, 3, 4, 5],[2,3,4,5,6]])
## print("Reshaped 1D Array:")
print(array_2d)
print(array_2d.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [14]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## identity matrix 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
## Attributes of numpy arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Item size(in bytes):", arr.itemsize)

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Data type: int64
Item size(in bytes): 8


In [19]:
### Numpy Vectorized Operation

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print("Vectorized Operation Result:", c)

Vectorized Operation Result: [5 7 9]


In [ ]:
## Universal Function - function that applies to the entire array element-wise
arr=np.array([1, 2, 3, 4, 5])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [21]:
## array slicing and Indexing

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:")
print(arr)

# Slicing the first two rows and first two columns
sliced_arr = arr[:2, :2]
print("Sliced Array (first two rows and columns):")
print(sliced_arr)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced Array (first two rows and columns):
[[1 2]
 [4 5]]
